import type { Metadata } from 'next'
import NavBar from '@/components/navbar/Navbar'
import Welcome from '@/components/bienvenida/bienvenida'
import Footer from '@/components/footer/footer'
import "./globals.css"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <Welcome/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
